# LAB 01: Làm quen với Pytorch
## Import thư viện pytorch

In [1]:
import torch

## Bài tập thực hành
### Bài 1: Tạo tensor cơ bản
Tạo một Tensor số nguyên kích thước 2 × 3 và hiển thị kết quả.


In [6]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print(a)

#Kích thước, số chiều, số lượng phần tử
print(f'Kích thước: {a.shape}')
print(f'Số chiều: {a.ndim}')
print(f'Kiểu dữ liệu: {a.dtype}')

tensor([[1., 2., 3.],
        [4., 5., 6.]])
Kích thước: torch.Size([2, 3])
Số chiều: 2
Kiểu dữ liệu: torch.float32


### Bài 2. Tạo các Tensor thường dùng
Thực hành tạo Tensor ngẫu nhiên, Tensor toàn số 0, toàn số 1 và ma trận đơn vị.

In [20]:
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.9651, 0.4499, 0.5780, 0.4638],
        [0.4173, 0.6815, 0.5949, 0.9114],
        [0.5931, 0.3744, 0.3589, 0.1246]])
tensor([[-1.3836, -1.9394,  0.8417, -0.5201],
        [-0.1345, -0.4731, -0.0371,  0.7873],
        [-1.6209, -0.1936,  0.8437,  0.9037]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


**Nhận xét**:
| `torch.rand()` | `torch.randn()` |
|-----|------|
| Ngẫu nhiên theo phân phối đều | Ngẫu nhiên theo phân phối chuẩn |
| Các giá trị trong `[0,1)` có xác suất như nhau | Giá trị tập trung quanh `0`, xa `0` thì xác suất càng loãng|

In [21]:
# Tạo một tensor 5 x 5 với tất cả các phần tử bằng 10
f = torch.full((5, 5), 10)
print(f)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


### Bài 3. Kiểm tra thông tin Tensor
Sử dụng shape, size(), ndim và dtype để kiểm tra các thuộc tính của Tensor.


In [23]:
a = torch.zeros(2, 3, 4)

print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


Ý nghĩa của **`torch.Size([2,3,4])`**: cho thấy kích thước của các chiều, mô tả cách dữ liệu được tổ chức: gồm 2 khối chứa 3 hàng, mỗi hàng chứa 4 phần tử

### Bài 4. Slicing và Indexing
Truy xuất một phần dữ liệu từ Tensor nhiều chiều.

In [24]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[-0.0287,  0.1965, -0.8072, -1.3639,  0.7018],
         [-0.3413,  0.2299,  1.1859, -0.7689,  1.9432],
         [-1.3214, -0.3775, -0.4404,  0.0190, -0.6504],
         [ 1.5359, -0.0671,  1.0471, -1.4076,  0.8688]],

        [[ 0.1139,  0.7473,  0.4312, -1.2985,  0.2972],
         [ 0.2156,  0.4866,  0.7348, -0.2215,  0.2581],
         [-0.3924,  2.1409,  2.2323,  0.1255,  1.6191],
         [ 2.4656,  0.2282,  2.4943,  0.1555,  0.6607]],

        [[-1.4763,  0.5179, -0.8514, -0.1100, -1.4297],
         [-1.1632,  0.6856,  0.1629, -0.4606,  2.3350],
         [ 1.8538, -1.2515,  0.0374, -0.3342, -0.5283],
         [-1.1420, -0.8290,  0.1687,  0.6328, -0.9787]]])

Tensor a[1]:
tensor([[ 0.1139,  0.7473,  0.4312, -1.2985,  0.2972],
        [ 0.2156,  0.4866,  0.7348, -0.2215,  0.2581],
        [-0.3924,  2.1409,  2.2323,  0.1255,  1.6191],
        [ 2.4656,  0.2282,  2.4943,  0.1555,  0.6607]])

Tensor a[1:, 2:4]:
tensor([[[-0.3924,  2.1409,  2.2323,  0.1255,  1.6

- Shape của `a[1]` là kích thước của dim0(chiều 1) lấy index 1 `torch.Size([4,5])`
- Shape của `a[1:, 2:4]` là kích thước của dim0(chiều 1) lấy index từ 1 và dim1(chiều 2) lấy index 2,3 `torchSize([2,2,5])`
- Cách lấy 2 phần tử cuối cùng trên chiều thứ 3(dim2) là `a[:,:,-2:]`


In [25]:
print("Shape a[1]:", a[1].shape)
print("Shape a[1:, 2:4]:", a[1:, 2:4].shape)
print(a[:,:,-2:])

Shape a[1]: torch.Size([4, 5])
Shape a[1:, 2:4]: torch.Size([2, 2, 5])
tensor([[[-1.3639,  0.7018],
         [-0.7689,  1.9432],
         [ 0.0190, -0.6504],
         [-1.4076,  0.8688]],

        [[-1.2985,  0.2972],
         [-0.2215,  0.2581],
         [ 0.1255,  1.6191],
         [ 0.1555,  0.6607]],

        [[-0.1100, -1.4297],
         [-0.4606,  2.3350],
         [-0.3342, -0.5283],
         [ 0.6328, -0.9787]]])


### Bài 5. Reshape và Flatten
Thay đổi hình dạng Tensor mà không làm thay đổi số phần tử.

In [26]:
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[-0.2271, -0.8819,  0.2459,  0.3112],
        [-0.4471,  1.0565,  1.9909, -0.4494],
        [-0.3463, -0.4320, -1.1624, -0.8651]])

Flatten:
tensor([-0.2271, -0.8819,  0.2459,  0.3112, -0.4471,  1.0565,  1.9909, -0.4494,
        -0.3463, -0.4320, -1.1624, -0.8651])

Reshape to 3 x 2 x 2:
tensor([[[-0.2271, -0.8819],
         [ 0.2459,  0.3112]],

        [[-0.4471,  1.0565],
         [ 1.9909, -0.4494]],

        [[-0.3463, -0.4320],
         [-1.1624, -0.8651]]])
